#!/bin/bash
STAGE=$1

source .env.$STAGE

SRC=src
OUT=out
BROWSERIFY=node_modules/.bin/browserify
TACHYONS=node_modules/tachyons/css/tachyons.min.css
EXORCIST=node_modules/.bin/exorcist

rm -rf $OUT
mkdir -p $OUT

$BROWSERIFY $SRC/index.js --debug | $EXORCIST $OUT/index.bundle.js.map > $OUT/index.bundle.js

eval "cat <<EOF
$(<index.html)
EOF
" 2> /dev/null >$OUT/index.html
cp img_trans.gif $OUT
cp styling.css $OUT
cp $TACHYONS $OUT
