#!/bin/bash

mkdir pokeapi_cache_sprites_trozei

for ((i=$1;i<=$2;i++)); do
	echo "getting $i"
    curl "http://www.serebii.net/battletrozei/pokemon/$i.png" > "sprites/pokeapi_cache_sprites_trozei/$i.png"
done