#!/bin/bash

mkdir pokeapi_cache_sprites_official_pics

for ((i=$1;i<=$2;i++)); do
	echo "getting $i"
    curl "http://www.serebii.net/art/th/$i.png" > "sprites/pokeapi_cache_sprites_official_pics/$i.png"
done