#!/bin/bash

mkdir pokeapi_cache_sprites_gold

for ((i=$1;i<=$2;i++)); do
	echo "getting $i"
    curl "http://www.serebii.net/pokearth/sprites/gold/$i.png" > "sprites/pokeapi_cache_sprites_gold/$i.png"
done