#!/bin/bash

mkdir pokeapi_cache_sprites_bw_shiny

for ((i=$1;i<=$2;i++)); do
	echo "getting $i"
    curl "http://www.serebii.net/Shiny/BW/$i.png" > "sprites/pokeapi_cache_sprites_bw_shiny/$i.png"
done